### ISSUE TITLE
Can we add git commit count in GitInfo?

### ISSUE THREAD

**Issue by tiann** [danielschemmel/build-info#11]
`git rev-list --count HEAD`

**Comment by danielschemmel** [comment]
I finally had a look at this request, and - as I expected - it can at most be an opt-in feature, as git needs to actually iterate over the parents to count them, which is quite expensive for large repositories:

```console
$ time git rev-list --count HEAD
449735

________________________________________________________
Executed in    2.48 secs    fish           external
   usr time    2.41 secs  732.00 micros    2.41 secs
   sys time    0.05 secs  114.00 micros    0.05 secs
```

I am not sure whether this information is really relevant enough to add it as an opt-in metric.
