### ISSUE TITLE
Create new release with bumped git2 dependency

### ISSUE THREAD

**Issue by epilys** [danielschemmel/build-info#12]

**Comment by danielschemmel** [comment]
`0.0.31` should use `git2` version (`0.17`)

**Comment by epilys** [comment]
Sorry I didn't clarify: crates.io still has 0.0.30

**Comment by danielschemmel** [comment]
Well, that is what I get for leaving a deploy unchecked ;).

`0.0.31` should now be on crates.io as well.

**Comment by epilys** [comment]
thanks so much!
