### ISSUE TITLE
[Feature Request]: DependencyDepth Workspaces

### ISSUE THREAD

**Issue by lexi-the-cute** [danielschemmel/build-info#17]
DependencyDepth should allow optionally including dependencies of workspaced dependencies while using DependencyDepth of 0. This'll allow getting the direct dependencies of all crates within a project without including the dependencies of the dependencies

**Comment by danielschemmel** [comment]
build-info works as in a build-script and is thus linked to a crate, not a workspace. Nothing should stop you from running build-info in each crate in your build-script. I am  somewhat hesitant at opening the can of worms that is workspaces even more than is already necessary, but if you have an actual design to propose, I will still consider it.

**Comment by lexi-the-cute** [comment]
My design proposal is, give a Vector of crates and say, i want to start from these crates and go depth 0 from those crates

For example:

```rust
fn generate_build_info() {
    // https://github.com/danielschemmel/build-info/issues/17
    // https://github.com/danielschemmel/build-info/issues/18
    let mut depth: DependencyDepth = DependencyDepth::Depth(0); // Set to 0
    let starting_crates: Vec<&str> = vec!["catgirl-engine", "catgirl-engine-client", "catgirl-engine-server"];

    // Custom environment variable to speed up writing code
    let rust_analyzer: bool = matches_environment_var("RUST_ANALYZER", "true");
    if rust_analyzer {
        depth = DependencyDepth::None;
    }

    build_info_build::build_script()
        .collect_dependencies(depth)
        .starting_crates(starting_crates);
}
```

The idea is, instead of just `catgirl-engine` being the starting crate like it is now, I can choose more than one and start the depth from there. I already filter out "catgirl-engine", "catgirl-engine-client", "catgirl-engine-server" from the client side code since I treat all 3 crates as one for the purposes of displaying my dependencies when displaying their licenses and versions

**Comment by lexi-the-cute** [comment]
I ended up combining the dependencies list from all the crates after generating them individually. This is the commit I just made to do this. https://github.com/lexi-the-cute/catgirl-engine/commit/ee824242de155123989ac635a274250cf0920a2a

**Comment by danielschemmel** [comment]
Great, that is how I thought it should work.

You can get rid of a bit of boilerplate code by directly specifying the function as public:
```rust
build_info::build_info!(pub fn build_info);
```

Also, as of 0.0.35, the rust-analyzer workaround should not be necessary anymore.

**Comment by lexi-the-cute** [comment]
thanks! the missing doc comment warnings appear when i set it to pub directly. im working on figuring out how to fix it
