### ISSUE TITLE
[Feature Request]: DependencyDepth optionally exclude build only dependencies

### ISSUE THREAD

**Issue by lexi-the-cute** [danielschemmel/build-info#18]
DependencyDepth should optionally allow people to exclude dependencies only used for building. This'll allow removing crates not built into the binary itself like cbindgen and cc

**Comment by danielschemmel** [comment]
Yes, that sounds reasonable.

**Comment by danielschemmel** [comment]
Note: this should be a new option rather than a change to the general dependency depth limit

**Comment by danielschemmel** [comment]
This feature is implemented in cc2da9a8b598b20388e0256f26dd7af968a8e90c.
