### ISSUE TITLE
OPT_LEVEL=z is not supported

### ISSUE THREAD

**Issue by daniel-wong-dfinity-org** [danielschemmel/build-info#7]
The [optimization_level](https://github.com/danielschemmel/build-info/blob/f289fcb3d6149108a6561de6caab9d375558794c/build-info-common/src/lib.rs#L45) field in BuildInfo does not handle s or z as possible optimization levels, [but they are allowed](https://stackoverflow.com/questions/45608392/what-do-the-optimization-levels-os-and-oz-do-in-rustc).

Not sure if anything backwards compatible can be done about this, but IIUC, that is not possible due to the fact that BuildInfo fields are all pub (not sure about this, because I am new to Rust). Still, it would be good for this issue to be filed, in case a) others run into this b) they really want s/z to be supported (and can +1 this issue to show their support).

**Comment by danielschemmel** [comment]
Yep, looks like you are totally right. a7f31acf71f1770237bde8356ea39fca90943724 should fix this problem and will be included in the next release (which will probably be 0.0.26).

**Comment by daniel-wong-dfinity-org** [comment]
Any idea when that might go out?

**Comment by danielschemmel** [comment]
0.0.26 is now published
