### ISSUE TITLE
Hopefully the `target-features` can be collected

### ISSUE THREAD

**Issue by PsiACE** [danielschemmel/build-info#9]
https://doc.rust-lang.org/reference/conditional-compilation.html#target_feature

I think it is necessary to record `CARGO_CFG_TARGET_FEATURE` in the build information to help us learn more.

**Comment by danielschemmel** [comment]
Can you check if aee0d6fb9f9c14eb6c7463f4b47928c5bf3929ed provides the information you were looking for?

**Comment by danielschemmel** [comment]
Issue closed as stale
